# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviesApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MoviesApp
    pod 'Alamofire', '~> 4.7'
    pod 'AlamofireImage', '~> 3.3'
    pod 'SwiftyJSON', '~> 4.0'

end
